### ISSUE TITLE
Could not load library - pg_duckdb

### ISSUE THREAD

**Issue by sindile** [pgsty/extension#16]
Thanks for your awesome repo.

I have build a docker containers using postgres:17-bookworm and include your repo. The installation for pg_duckdb works fine.

I can also confirm that the extension is installed :
postgres=# SELECT * FROM pg_available_extensions WHERE name = 'pg_duckdb';
   name    | default_version | installed_version |           comment           
-----------+-----------------+-------------------+-----------------------------
 pg_duckdb | 0.1.0           |                   | DuckDB Embedded in Postgres
(1 row)

I added pg_duckb via this in my docker-compose file:
command: postgres -c shared_preload_libraries='pg_duckdb'

This is the error I observe in my container logs:
ERROR:  could not load library "/usr/lib/postgresql/17/lib/pg_duckdb.so": /usr/lib/postgresql/17/lib/pg_duckdb.so: undefined symbol: _ZTIN6duckdb28SimpleNamedParameterFunctionE

Here is my complete Dockerfile that I am using:
FROM postgres:17-bookworm

# Do not split the description, otherwise we will see a blank space in the labels
LABEL name="PostgreSQL Container Images" \
    vendor="The CloudNativePG Contributors" \
    version="${PG_VERSION}" \
    release="9" \
    summary="PostgreSQL Container images." \
    description="This Docker image contains PostgreSQL and Barman Cloud based on Postgres 17.2-bookworm." \
    org.opencontainers.image.description="This Docker image contains PostgreSQL and Barman Cloud based on Postgres 17.2-bookworm."

# Copy the requirements file first to leverage Docker cache
COPY requirements.txt /

# Install dependencies, add external repository, and clean up
RUN set -xe; \
    # Set up APT repositories (including Pigsty) before installing packages
    mkdir -p /etc/apt/keyrings; \
    # Update package lists, install necessary dependencies and packages
    apt-get update; \
    apt-get install -y --no-install-recommends \
    wget gnupg2 build-essential python3-dev libsnappy-dev \
    python3-pip python3-psycopg2 python3-setuptools; \
    # Download and verify the GPG key by checking the fingerprint
    wget --quiet -O - https://repo.pigsty.io/key | gpg --dearmor -o /etc/apt/keyrings/pigsty.gpg; \
    # Add repository using the trusted GPG key
    echo "deb [signed-by=/etc/apt/keyrings/pigsty.gpg] https://repo.pigsty.io/apt/infra generic main" > /etc/apt/sources.list.d/pigsty-io.list; \
    echo "deb [signed-by=/etc/apt/keyrings/pigsty.gpg] https://repo.pigsty.io/apt/pgsql/bookworm bookworm main" >> /etc/apt/sources.list.d/pigsty-io.list; \
    # Update package lists, install necessary dependencies and packages
    apt-get update; \
    apt-get install -y --no-install-recommends \
    postgresql-${PG_MAJOR}-pgaudit \
    postgresql-${PG_MAJOR}-pgvector \
    postgresql-${PG_MAJOR}-pg-failover-slots \
    postgresql-${PG_MAJOR}-postgis-3 \
    postgresql-${PG_MAJOR}-postgis-3-scripts \
    postgresql-plpython3-${PG_MAJOR} \
    postgresql-${PG_MAJOR}-pgrouting \
    postgresql-${PG_MAJOR}-cron \
    postgresql-${PG_MAJOR}-ogr-fdw \
    postgresql-${PG_MAJOR}-http \
    postgresql-${PG_MAJOR}-partman \
    postgresql-${PG_MAJOR}-pg-uuidv7 \
    postgresql-${PG_MAJOR}-pgnodemx \
    postgresql-${PG_MAJOR}-anonymizer \
    postgresql-${PG_MAJOR}-pglogical* \
    postgresql-${PG_MAJOR}-h3 \
    postgresql-${PG_MAJOR}-similarity \
    postgresql-${PG_MAJOR}-pg-ivm \
    postgresql-${PG_MAJOR}-pg-hint-plan \
    postgresql-${PG_MAJOR}-repack \
    postgresql-${PG_MAJOR}-ddlx \
    postgresql-${PG_MAJOR}-hypopg \
    postgresql-${PG_MAJOR}-squeeze \
    postgresql-${PG_MAJOR}-plr \
    postgresql-${PG_MAJOR}-pg-stat-kcache \
    postgresql-${PG_MAJOR}-pg-duckdb \
    postgresql-${PG_MAJOR}-pg-parquet; \
    # # Install Python packages from the requirements file
    # pip3 install --break-system-packages --upgrade pip; \
    pip3 install --break-system-packages --no-deps -r requirements.txt; \
    # Clean up the build dependencies and temporary files to reduce image size
    apt-get remove -y --purge --autoremove build-essential python3-dev libsnappy-dev; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/* /tmp/*; \
    # Create initialization directory for PostgreSQL
    mkdir -p /docker-entrypoint-initdb.d;

# # Copy init scripts
COPY ./initdb-postgis.sh /docker-entrypoint-initdb.d/10_postgis.sh
COPY ./update-postgis.sh /usr/local/bin

# # Change user ID for postgres and ensure permissions are correct
RUN usermod -u 26 postgres; \
    chown -R postgres:postgres /docker-entrypoint-initdb.d /usr/local/bin

# Switch to non-root user
USER 26

**Comment by Vonng** [comment]
duckdb_fdw and libduckdb are conflict with pg_duckdb, make sure that is not installed. By the way pg_duckdb 0.2.0 will be publish tomorrow, Check tomorrow to see if it is fixed.

**Comment by Vonng** [comment]
now pg_duckdb 0.2.0 is public available

**Comment by sindile** [comment]
Have updated to the latest pg_duckdb 0.2.0 and still facing the same issue. I am not sure what is the problem, but will keep trying.

**Comment by Vonng** [comment]
This extension has been compiled for RockyLinux 8.9+, 9.3+, Ubuntu 22.04.3+, and Debian 12.7+. If your operating system's minor version is below these, it may not work due to an outdated C++ standard library version resulting in missing symbols.

Besides, I Need more information, which PG major version (14-17), on which OS distro (cat /etc/os-release) and which arch (x86_64 or arm64).

**Comment by sindile** [comment]
`cat /etc/os-release `
```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
Debian minor version 12.5

`uname -m`
`x86_64`

PG major version 17

I am usin the official postgres docker image - https://github.com/docker-library/postgres/blob/0b87a9bbd23f56b1e9e863ecda5cc9e66416c4e0/17/bookworm/Dockerfile

**Comment by Vonng** [comment]
I've repreduced the problem, Will update a new version today.

**Comment by Vonng** [comment]
recompiled and updated, try again

**Comment by sindile** [comment]
I can confirm the extension is now working, Thank you.
